//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectId { get; set; }
        public Nullable<int> ProjectTypeId { get; set; }
        public Nullable<int> ProjectStatusId { get; set; }
        public Nullable<bool> IsInternalIT { get; set; }
        public string ProjectName { get; set; }
        public string ProjectOwner { get; set; }
        public string ProjectManager { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> ProjectPhaseId { get; set; }
        public Nullable<int> PhasePercentComplete { get; set; }
        public Nullable<System.DateTime> PhaseEndDate { get; set; }
        public Nullable<int> OverallPercentComplete { get; set; }
        public Nullable<System.DateTime> ProjectEndDate { get; set; }
        public Nullable<bool> IsWaiting { get; set; }
        public string Comments { get; set; }
        public string ProjectDescription { get; set; }
    
        public virtual ProjectPhase ProjectPhase { get; set; }
        public virtual ProjectStatus ProjectStatus { get; set; }
        public virtual ProjectType ProjectType { get; set; }
    }
}
